name: Lint
on:
  push:
    branches: [ main ]
    paths-ignore:
      - docs/**

  pull_request:
    branches: [ main ]
    paths-ignore:
      - docs/**

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pip install -e .[test]

    - name: Lint with pre-commit
      run: pre-commit run --all-files
